config/routes.rb
Rails.application.routes.draw do

  root 'poems#generate'

  resources :poems

end

app/models/image.rb
class Image < ActiveRecord::Base
  validates :url, presence: :true
  def self.grab_random
    image = find_by_sql "SELECT * FROM images ORDER BY random() LIMIT 1"
    pic = image.first
    return pic ? pic.url : nil
  end
end

app/models/poem.rb
class Poem < ActiveRecord::Base
  validates :name, presence: :true
  class << self

    def generate_random
      song_data = random_song_slices
      new(:name => random_name_from(song_data), :data => song_data)
    end

    private

    def random_name_from(string)
      string.split(" ").sample
    end

    def random_song_slices
      SongSlice.random_set(rand(3..15)).map(&:chunk).join("\n")
    end


  end
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  class << self
    def grab_random
      find_by_sql("SELECT quote_text FROM quotes ORDER BY random() LIMIT 1").first
    end
  end
end

app/models/song.rb
class Song < ActiveRecord::Base
  has_many :song_slices
end

app/models/song_slice.rb
class SongSlice < ActiveRecord::Base
  belongs_to :song

  class << self

    def random_set(number)
      find_by_sql "SELECT * FROM song_slices ORDER BY random() LIMIT #{number}"
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/poems_controller.rb
class PoemsController < ApplicationController
  before_action :set_poem, only: [:show, :destroy]
  def generate
    @poem = Poem.new
    @quote = Quote.grab_random.quote_text
  end

  def create
    @poem = Poem.new(poem_params)

    respond_to do |format|
      if @poem.save
        format.html { redirect_to poem_path(@poem) }
      end
    end
  end

  def new
    @poem = Poem.generate_random
    @image_url = Image.grab_random
  end

  def show
  end

  private

  def set_poem
    @poem = Poem.find(params[:id])
  end

  def poem_params
    params.require(:poem).permit(:name, :data)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NiceIceMaybe</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="row">
    <div class="col-xs-12">
      <div class="col-xs-12">
        <%= yield %>
      </div>
    </div>
  </div>

</body>
</html>

app/views/poems/generate.html.erb
<%= simple_form_for @poem, :url => new_poem_path, :method => :get do |f| %>
  <%= f.button :submit, "generate!" %>
  <div class="quoteContainer">
  	<p><%= @quote %></p>
  </div>
<% end %>

app/views/poems/new.html.erb
<div class='row'>
  <div class='col-xs-12'>
    <%= simple_form_for @poem do |f| %>
      <div class='row'>
        <div class='col-xs-6'>
          <br>
          <%= f.input :name %>
          <br>
          <%= f.input :data , input_html: { class: "textbox" } %>
          <br>
        </div>
        <div class='col-xs-6'>
          <%= f.hidden_field :image_url, value: @poem.image_url || @image_url %>
          <img class='image' src=<%= @poem.image_url || @image_url %>></img>
        </div>
      </div>
      <%= f.button :submit, "save!" %>
      <%= link_to "regenerate!", new_poem_path, class: "btn btn-primary"  %>
    <% end %>
  </div>
</div>

app/views/poems/show.html.erb
<%= @poem.name %>
<%= simple_format(@poem.data) %>